# Generated by Django 5.0.9 on 2024-11-12 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breastcancer', '0002_remove_examen_prediction_prediccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='modelo',
        ),
    ]
