# Generated by Django 4.2 on 2024-12-15 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breastcancer", "0003_remove_examen_modelo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examen",
            options={"verbose_name_plural": "Exámenes"},
        ),
        migrations.AlterModelOptions(
            name="prediccion",
            options={"verbose_name_plural": "Predicciones"},
        ),
    ]
