"""
Django settings for clinicarobles project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sboiv9p5dzvpk5k_a#7**_pz$xqh-hctd26=lb2&4saw9=6=o='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'breastcancer',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clinicarobles.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clinicarobles.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'clinicarobles',
        'USER': 'clinicarobles_owner',
        'PASSWORD': '50CbIlLQvSNB',
        'HOST': 'ep-super-bar-a5pdt0zt.us-east-2.aws.neon.tech',
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}
CSRF_TRUSTED_ORIGINS = [
    'https://localhost:8000',
    'https://literate-space-rotary-phone-5pvr5xv749ghpgvx-8000.app.github.dev/',
    'https://clinica-robles-sistema-deteccion.vercel.app',
    'https://gross-barbabra-ilan-bc39a3dd.koyeb.app',
    'https://animated-space-pancake-67v5w4vx97pc5j49-5173.app.github.dev',
    'https://animated-space-pancake-67v5w4vx97pc5j49-5173.app.github.dev/predecir',
]
ALLOWED_HOSTS = [
    'gross-barbabra-ilan-bc39a3dd.koyeb.app',
    'https://animated-space-pancake-67v5w4vx97pc5j49-5173.app.github.dev/predecir',
    'localhost',
    'literate-space-rotary-phone-5pvr5xv749ghpgvx-8000.app.github.dev',
    ]
CORS_ALLOWED_ORIGINS = [
    'https://localhost:8000',
    'https://literate-space-rotary-phone-5pvr5xv749ghpgvx-8000.app.github.dev',
    'https://clinica-robles-sistema-deteccion.vercel.app',
    'https://gross-barbabra-ilan-bc39a3dd.koyeb.app',
    'https://animated-space-pancake-67v5w4vx97pc5j49-5173.app.github.dev',
]
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
